CREATE VIEW "art_info" (
    "ROWKEY" VARCHAR PRIMARY KEY,
    "metadata"."GalleryNumber" VARCHAR,
    "metadata"."accessionNumber" VARCHAR,
    "metadata"."accessionYear" VARCHAR,
    "metadata"."additionalImages" VARCHAR,
    "metadata"."artistAlphaSort" VARCHAR,
    "metadata"."artistBeginDate" VARCHAR,
    "metadata"."artistDisplayBio" VARCHAR,
    "metadata"."artistDisplayName" VARCHAR,
    "metadata"."artistEndDate" VARCHAR,
    "metadata"."artistGender" VARCHAR,
    "metadata"."artistNationality" VARCHAR,
    "metadata"."artistPrefix" VARCHAR,
    "metadata"."artistRole" VARCHAR,
    "metadata"."artistSuffix" VARCHAR,
    "metadata"."artistULAN_URL" VARCHAR,
    "metadata"."artistWikidata_URL" VARCHAR,
    "metadata"."city" VARCHAR,
    "metadata"."classification" VARCHAR,
    "metadata"."constituents" VARCHAR,
    "metadata"."country" VARCHAR,
    "metadata"."county" VARCHAR,
    "metadata"."creditLine" VARCHAR,
    "metadata"."culture" VARCHAR,
    "metadata"."department" VARCHAR,
    "metadata"."dimensions" VARCHAR,
    "metadata"."dynasty" VARCHAR,
    "metadata"."excavation" VARCHAR,
    "metadata"."geographyType" VARCHAR,
    "metadata"."isHighlight" BOOLEAN,
    "metadata"."isPublicDomain" BOOLEAN,
    "metadata"."isTimelineWork" BOOLEAN,
    "metadata"."linkResource" VARCHAR,
    "metadata"."locale" VARCHAR,
    "metadata"."locus" VARCHAR,
    "metadata"."measurements" VARCHAR,
    "metadata"."medium" VARCHAR,
    "metadata"."metadataDate" VARCHAR,
    "metadata"."objectBeginDate" VARCHAR,
    "metadata"."objectDate" VARCHAR,
    "metadata"."objectEndDate" VARCHAR,
    "metadata"."objectID" VARCHAR,
    "metadata"."objectName" VARCHAR,
    "metadata"."objectURL" VARCHAR,
    "metadata"."objectWikidata_URL" VARCHAR,
    "metadata"."period" VARCHAR,
    "metadata"."portfolio" VARCHAR,
    "metadata"."primaryImage" VARCHAR,
    "metadata"."primaryImageSmall" VARCHAR,
    "metadata"."region" VARCHAR,
    "metadata"."reign" VARCHAR,
    "metadata"."repository" VARCHAR,
    "metadata"."rightsAndReproduction" VARCHAR,
    "metadata"."river" VARCHAR,
    "metadata"."state" VARCHAR,
    "metadata"."subregion" VARCHAR,
    "metadata"."tags" VARCHAR,
    "metadata"."title" VARCHAR
);

## example1
SELECT "ROWKEY", 
       "metadata"."title", 
       "metadata"."artistDisplayName", 
       "metadata"."objectDate" 
FROM "art_info" 
LIMIT 10;

## example2
SELECT "ROWKEY", 
       "metadata"."title", 
       "metadata"."artistDisplayName", 
       "metadata"."objectDate",
       "metadata"."primaryImage"
FROM "art_info" 
LIMIT 1;
